#
# Glauber 2025
#
# Template: buildimageanddeployacr.yml
# Objetivo: Gera uma imagem Docker, escaneia vulnerabilidades com Trivy e faz o deploy no Azure Container Registry (ACR).
#           Opcionalmente, reinicia uma Azure Container App para utilizar a nova imagem.
#
# Parâmetros (Inputs):
#   ACR_NAME                : (Obrigatório) Nome do Azure Container Registry.
#   IMAGE_NAME              : (Obrigatório) Nome da imagem a ser gerada.
#   DOCKER_FILE             : (Obrigatório) Caminho/Nome do Dockerfile.
#   TRIVY_SEVERITY          : (Opcional) Nível de severidade para falha (CRITICAL, HIGH, MEDIUM, LOW). Default: CRITICAL.
#   RESTART_CONTAINER       : (Opcional) 'S' para reiniciar a Azure Container App após o deploy. Default: 'N'.
#   AZURE_RESOURCE_GROUP    : (Opcional) Resource Group da Container App (Obrigatório se RESTART_CONTAINER='S').
#   AZURE_CONTAINERAPP_NAME : (Opcional) Nome da Container App (Obrigatório se RESTART_CONTAINER='S').
#
# Secrets:
#   DOCKER_USERNAME         : (Obrigatório) Usuário/Service Principal para login no ACR.
#   DOCKER_PASSWORD         : (Obrigatório) Senha/Secret para login no ACR.
#   AZURE_CREDENTIALS       : (Opcional) JSON de credenciais do Azure (Obrigatório se RESTART_CONTAINER='S').
#
 
name: Generate Image
 
on:
  workflow_call:
    inputs:
      ACR_NAME:
        description: "Nome do Azure Container registry"
        required: true
        type: string
        default: ''
 
      IMAGE_NAME:
        description: "Nome da imagem a ser gerada"
        required: true
        type: string
        default: ''
 
      DOCKER_FILE:
        description: "Nome do arquivo dockerfile que contém a definição da imagem"
        required: true
        type: string
        default: ''  
 
      TRIVY_SEVERITY:
        description: "Nível de severidade que deve quebrar a pipeline (CRITICAL, HIGH, MEDIUM, LOW)"
        required: false
        type: string
        default: 'CRITICAL'
 
      RESTART_CONTAINER:
        description: "Reiniciar ACA?"
        required: false
        type: string
        default: 'N'
 
      AZURE_RESOURCE_GROUP:
        description: "Nome do Resource Group do Azure Container App"
        required: false
        type: string
        default: ''
 
      AZURE_CONTAINERAPP_NAME:
        description: "Nome do Azure Container App"
        required: false
        type: string
        default: ''
 
    secrets:
      DOCKER_USERNAME:
        description: "Usuário do ACR"
        required: true
 
      DOCKER_PASSWORD:
        description: "Senha do ACR"
        required: true
 
      AZURE_CREDENTIALS :
        description: "Azure Credentials JSON para login"
        required: false 
 
jobs:
  Deploy-acr:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout repository 
        uses: actions/checkout@v3 
        with:
          fetch-depth: '0'
 
      - name: 🚀 Build an image ${{ github.run_number }}
        run: docker build -t  ${{ inputs.ACR_NAME }}/${{ inputs.IMAGE_NAME }}:${{ github.run_number }} -t ${{ inputs.ACR_NAME }}/${{ inputs.IMAGE_NAME }}:latest -f ${{ inputs.DOCKER_FILE }} .
 
      - name: 🔍 Trivy - Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.ACR_NAME }}/${{ inputs.IMAGE_NAME }}:latest
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: ${{ inputs.TRIVY_SEVERITY }}
          exit-code: '1'
 
      - name: 🔍 Trivy - Detailed Report (on failure)
        if: failure()
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.ACR_NAME }}/${{ inputs.IMAGE_NAME }}:latest
          format: 'table'
          severity: ${{ inputs.TRIVY_SEVERITY }}
          exit-code: '0'
 
      - name: 📋 Upload Trivy SARIF report
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
 
      - name: ❌ Security Check Failed
        if: failure()
        run: |
          echo "🚨 VULNERABILIDADES ENCONTRADAS! 🚨"
          echo ""
          echo "A pipeline foi interrompida porque foram encontradas vulnerabilidades"
          echo "de nível '${{ inputs.TRIVY_SEVERITY }}' ou superior na imagem."
          echo ""
          echo "🔍 Para ver os detalhes:"
          echo "- Verifique o log da etapa 'Trivy - Detailed Report'"
          echo "- Acesse a aba Security > Code scanning alerts no GitHub"
          echo ""
          echo "✅ Como corrigir:"
          echo "- Atualize as dependências da aplicação"
          echo "- Use uma imagem base mais recente"
          echo "- Remova pacotes desnecessários"
          echo ""
          exit 1
         
      - name: 🚀 Login to ACR 
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ inputs.ACR_NAME }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 
      
      - name: 🚀 Push an image latest
        run: docker push ${{ inputs.ACR_NAME }}/${{ inputs.IMAGE_NAME }}:latest
     
      - name: 🚀 Push an image 
        run: docker push ${{ inputs.ACR_NAME }}/${{ inputs.IMAGE_NAME }}:${{ github.run_number }}
 
      - name: Docker Logout 
        run: docker logout ${{ inputs.ACR_NAME }}
 
      - name: 🔐 Azure login (OIDC) 
        if: ${{ inputs.RESTART_CONTAINER == 'S' }} 
        uses: azure/login@v2 
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
         
          
 
      - name: 🔁 Restart Azure Container Apps revisions (latest image) 
        if: ${{ inputs.RESTART_CONTAINER == 'S' }} 
        uses: azure/cli@v2 
        with: 
          azcliversion: latest
          inlineScript: | 
            set -euo pipefail 
            RG="${{ inputs.AZURE_RESOURCE_GROUP }}" 
            APP="${{ inputs.AZURE_CONTAINERAPP_NAME }}" 
 
            if [ -z "$RG" ] || [ -z "$APP" ]; then 
              echo "AZURE_RESOURCE_GROUP e AZURE_CONTAINERAPP_NAME são obrigatórios quando RESTART_CONTAINER = 'S'." 
              exit 1 
            fi 
 
            echo "💡 Garantindo extensão containerapp instalada..." 
            az extension add --name containerapp --yes --upgrade 
 
            echo "ℹ️ Container App: $APP | RG: $RG" 
            IMG=$(az containerapp show -n "$APP" -g "$RG" --query "properties.template.containers[0].image" -o tsv || true) 
            PULL=$(az containerapp show -n "$APP" -g "$RG" --query "properties.template.containers[0].imagePullPolicy" -o tsv || true) 
            echo "Imagem configurada: ${IMG:-desconhecida}" 
            echo "imagePullPolicy: ${PULL:-desconhecida}" 
 
            echo "🔎 Buscando revisões ativas..." 
            REVISIONS=$(az containerapp revision list -n "$APP" -g "$RG" --query "[?properties.active==\`true\`].name" -o tsv) 
            if [ -z "$REVISIONS" ]; then 
              echo "Nenhuma revisão ativa encontrada para $APP." 
              exit 1 
            fi 
 
            for REV in $REVISIONS; do 
              echo "🔁 Reiniciando revisão: $REV" 
              az containerapp revision restart -n "$APP" -g "$RG" --revision "$REV" 
            done 
 
            echo "✅ Reinício solicitado para todas as revisões ativas."
